#!/bin/bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
#a=1
#for line in $(/usr/bin/nvidia-settings -q all -t 2> /dev/null | egrep 'GPUCoreTemp|FanSpeedRPM|DedicatedGPUMemory' | sed 's/\s*//g'); do
#  if [[ "$line" =~ "GPUCoreTemp" ]]; then
#    line=$(echo -n "$line" | sed "s/GPUCoreTemp/GPUCoreTemp${a}/")
#    (( a++ ))
#  fi
#  echo -en "$line "
#done
#echo
nvidia-smi --query-gpu=temperature.gpu,memory.used,memory.free -g 0 --format=csv,noheader,nounits | sed 's/,//g' | awk '{print "tempc:"$1" memused:"$2*1000000" memfree:"$3*1000000}'
